apiVersion: v1
kind: Service
metadata:
  name: raot-bot-service
spec:
  type: NodePort 
  selector:
    app: raot-bot
  ports:
  - name: vnc
    protocol: TCP
    port: 5900
    targetPort: 5900
  - name: game
    protocol: TCP
    port: 15939
    targetPort: 15937